spring:
  cloud:
    gateway:
      routes:
        - id: uri
          uri: https://google.com
          predicates:
            - Path=**
          filters:
            - RequestHeaderToRequestUri=location

